" File Header {{{1 ------------------------------------------------------------
" File: ~/.vimrc
" Author: Evan C. Ezell (evanezell595<at>gmail<dot>com)
" End File Header 1}}} --------------------------------------------------------
" Imports {{{1 ----------------------------------------------------------------
source ~/dots/vim/vim_functions.vim
" End Imports 1}}} ------------------------------------------------------------
" Vundle {{{1  ----------------------------------------------------------------
" Vundle vim plugin package manager setup
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" vim plugins from GitHub repos
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'chrisbra/csv.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
if executable('fzf')
    Plugin 'junegunn/fzf'
    Plugin 'junegunn/fzf.vim'
    Plugin 'airblade/vim-rooter'
endif

call vundle#end()
filetype plugin indent on
" End Vundle 1}}} -------------------------------------------------------------
" Airline {{{1 ----------------------------------------------------------------
" Airline status line / status line settings
let g:airline#extensions#tabline#enabled = 1

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ' :'
let g:airline_symbols.maxlinenr = '☰ '
" End Airline 1}}} ------------------------------------------------------------
" Mappings {{{1 ---------------------------------------------------------------
let mapleader="\<space>"
nnoremap <leader>w :w<cr>
nnoremap <leader>q :wq<cr>
nnoremap <leader>Q :q!<cr>
nnoremap <leader>s yiw:exe '%s/' . @" . '//g'<left><left><left>
nnoremap <leader>p :!!<cr><cr>
nnoremap <leader>l :set list!<cr>
nnoremap <leader>n :set number!<cr>
nnoremap <leader>r :set relativenumber!<cr>
nnoremap <leader>P :set paste!<cr>
nnoremap <leader>j ddp
nnoremap <leader>k ddkP
vnoremap <leader>j dp
vnoremap <leader>k dkP
nnoremap <leader>o o<esc>k
nnoremap <leader>O O<esc>j
nnoremap <leader>" ciw"<C-r>""<esc>
vnoremap <leader>" c"<C-r>""<esc>
nnoremap <leader>( ciw(<C-r>")<esc>
vnoremap <leader>( c(<C-r>")<esc>
nnoremap <leader>; ms$a;<esc>`s
nnoremap <leader>t :tabn 

" make it easier to exit mode
inoremap jj <esc>
cnoremap jj <esc>

" code reindention for whole file
noremap <F7> gg=G``
" End Mappings 1}}} -----------------------------------------------------------
" General {{{1 ----------------------------------------------------------------
set encoding=utf-8

" fold settings
set foldlevel=99
set foldmethod=marker

" indentation related stuff
set tabstop=8
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent

" file visualizations
set number
syntax on
colorscheme default
set colorcolumn=80
highlight ColorColumn ctermbg=DarkGray

set wildmenu " filename expansion
" End General 1}}} ------------------------------------------------------------
" Split-Screen {{{1 -----------------------------------------------------------
nnoremap <silent> <C-h> :call WinMove('h')<cr>
nnoremap <silent> <C-j> :call WinMove('j')<cr>
nnoremap <silent> <C-k> :call WinMove('k')<cr>
nnoremap <silent> <C-l> :call WinMove('l')<cr>
" End Split-Screen 1}}} -------------------------------------------------------
" Language Specific Settings {{{1 ---------------------------------------------
" Text/Markdown {{{2 ----------------------------------------------------------
autocmd BufNewFile,BufRead *.md,*.txt
    \ set textwidth=79 |
    \ inoremap #sig Evan Ezell<Enter>
               \Email: evanezell595@gmail.com<Enter>
               \Cell: 770.317.5977<esc>3k0
" End Text/Markdown 2}}} ------------------------------------------------------
" R {{{2 ----------------------------------------------------------------------
autocmd BufNewFile,BufRead *.R
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2 |
    \ set autoindent |
    \ set expandtab |
    \ set fileformat=unix
" End R 2}}} ------------------------------------------------------------------
" Python {{{2 -----------------------------------------------------------------
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |
    \ set fdm=indent
" End Python 2}}} -------------------------------------------------------------
" C/C++ {{{2 ------------------------------------------------------------------
autocmd Filetype c,cpp 
    \ inoremap #in #include |
    \ inoremap #d #define
" End C/C++ 2}}} --------------------------------------------------------------
" Lisp-Like {{{2 --------------------------------------------------------------
autocmd Filetype lisp set lisp
autocmd BufReadPost,BufNewFile *.scm set filetype=lisp
" End Lisp-Like 2}}} ----------------------------------------------------------
" Makefile {{{2 ---------------------------------------------------------------
autocmd FileType make 
    \ set noexpandtab |
    \ set shiftwidth=8 |
    \ set softtabstop=0
" End Makefile 2}}} -----------------------------------------------------------
" TypeScript {{{2 -------------------------------------------------------------
autocmd BufReadPost,BufNewFile *.ts set filetype=typescript
autocmd FileType typescript 
    \ set softtabstop=2 |
    \ set shiftwidth=2
" End TypeScript 2}}} ---------------------------------------------------------
" End Language Specific Settings 1}}} -----------------------------------------
